### PR TITLE
Fix memory leak in get_create_time()

### PR DESCRIPTION
**Pull request by unmole**

### CODE REVIEW

**Comment by k4rtik** [comment]
Good catch, thanks!

**Comment by nibrahim** [comment]
Thanks @unmole! Excellent catch. Shouldn't our valgrind runs have caught this?

**Comment by unmole** [comment]
@nibrahim Valgrind did report this.

**Comment by nibrahim** [comment]
Hmm. I thought I was quite diligent about running the entire thing with valgrind. I think we'll have to get more systematic about this.

**Pull request merged**
